### PR TITLE
feat: adjust activity logic

### PR DESCRIPTION
**Pull request by TTNguyenDev**
https://app.dework.xyz/nation3/development-guild-43499?taskId=c6f01d02-2aa4-417d-a321-3281c397d0df

### CODE REVIEW

**Comment by aahna-ashina** [comment]
Can you also run the script to see how these changes affect the generated CSV files?

**Comment by TTNguyenDev** [comment]
The code so that a Nation3 citizen becomes an "Active Citizen" only after 4 continuous weeks of activity, and to consider them "Inactive" if there are 2 continuous weeks of inactivity, you can modify the condition for determining the isActive and isInactive statuses
@aahna-ashina

**Comment by TTNguyenDev** [comment]
image
this is the nationcred-scores.csv

**Comment by TTNguyenDev** [comment]
Hi @aahna-ashina, please confirm: with this update, a citizen is considered to be active if they have contributed at least 1 hour in 2 weeks, and it has to happen within a month, correct? So, let's say they can contribute 1 hour in week 1 and 1 hour in week 4?

**Comment by TTNguyenDev** [comment]
Do we accept 0.5 hour in week 1 and 0.5 hour in week 2?

**Comment by TTNguyenDev** [comment]
image
Please check this file after changing the logic

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
> at least 2 hour per week

This is not correct.  We are still using the "1 hour per week" number.

**Comment by TTNguyenDev** [comment]
So the condition should be 
`week4 > 1 || week3 > 1`
right?
Currently, I'm using `week4 + week3 > 1`  @aahna-ashina please confirm

**Comment by aahna-ashina** [comment]
> So the condition should be 
> 
> `week4 > 1 || week3 > 1`
> 
> right?
> 
> Currently, I'm using `week4 + week3 > 1`  @aahna-ashina please confirm

@TTNguyenDev No, not right, because the citizen needs to have activity in 4 weeks _in sequence_.

This can happen in two ways:

- 5 weeks ago, and
- 4 weeks ago, and
- 3 weeks ago, and
- 2 weeks ago

or

- 4 weeks ago, and
- 3 weeks ago, and
- 2 weeks ago, and
- last week

**Comment by aahna-ashina** [comment]
Fixed in https://github.com/nation3/nationcred-datasets/pull/129

**Pull request closed without merging**
